### ISSUE TITLE
Ability to generate Segmentation Maps

### ISSUE THREAD

**Issue by unexpector** [erikKeresztes/gaugan.py#1]
This code is great, I am looking to get this to generate segmentation maps as well,  so I can convert a series of video frames.

Would it be possible to have a function added to use the  ability to take a real image and return a segmap?

I have tried playing with 
nvidia_gaugan_submit_real_image / nvidia_gaugan_return_segmap  

but it keeps giving me a 500 error.

**Comment by erikKeresztes** [comment]
If you're referring to the source map that gaugan uses to generate the images, it's just a simple PNG image, so if you want to convert a video you can just render it as separate PNG images and use ```processImage()``` on each frame

**Comment by erikKeresztes** [comment]
Unless I misunderstood and the problem is something else, I clarified what the  `image` argument is in the readme and added an example input.png with version 1.1

**Comment by elliottcandrew** [comment]
In the event that @erikKeresztes did misunderstand the question and @unexpector was hoping to upload real images in return for segmentation maps, the following works for me:

```
def segmentImage(image):

    # generate name for requests
    name = ''.join(random.choices(string.ascii_lowercase + string.digits, k=20))

    files = [
        ('file', (name + '.png', image, 'image/png'))
    ]

    requests.post(url + 'nvidia_gaugan_submit_real_image', data={'name': name}, files=files)

    r = requests.post(url + 'nvidia_gaugan_return_segmap', stream=True, data={'name': name})

    # print(r.text)

    if r.status_code != 200:
        # print(r.status_code)
        raise(RuntimeError(f'{http.client.responses[r.status_code]} ({r.status_code}) while processing image.'))

    r.raw.decode_content = True
    return r.raw.data


with open('frame000138.png', "rb") as fh:
    image = segmentImage(fh.read())

with open('output-map2.png', "wb") as fh:
    fh.write(image)
```
